# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0004_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighbourhood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood', to='neighbourhoodapp.Neighbourhood'),
        ),
    ]
