# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0005_auto_20181018_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_location',
            field=models.TextField(choices=[('London', 'London'), ('Liverpool', 'Liverpool'), ('Sheffield', 'Sheffield'), ('Manchester', 'Manchester'), ('Leeds', 'Leeds'), ('Nottingham', 'Nottingham'), ('Brighton', 'Brighton'), ('Bristol', 'Bristol'), ('Oxford', 'Oxford'), ('Cambridge', 'Cambridge')], default=0),
        ),
    ]
