# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourhoodapp', '0006_auto_20181018_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='occupants_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='population',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoodproject', to='neighbourhoodapp.Neighbourhood'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoodproject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighbourhood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoodbusiness', to='neighbourhoodapp.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_location',
            field=models.TextField(blank=True, choices=[('London', 'London'), ('Liverpool', 'Liverpool'), ('Sheffield', 'Sheffield'), ('Manchester', 'Manchester'), ('Leeds', 'Leeds'), ('Nottingham', 'Nottingham'), ('Brighton', 'Brighton'), ('Bristol', 'Bristol'), ('Oxford', 'Oxford'), ('Cambridge', 'Cambridge')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood', to='neighbourhoodapp.Neighbourhood'),
        ),
    ]
