# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0008_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_location',
            field=models.CharField(blank=True, choices=[('London', 'London'), ('Liverpool', 'Liverpool'), ('Sheffield', 'Sheffield'), ('Manchester', 'Manchester'), ('Leeds', 'Leeds'), ('Nottingham', 'Nottingham'), ('Brighton', 'Brighton'), ('Bristol', 'Bristol'), ('Oxford', 'Oxford'), ('Cambridge', 'Cambridge')], default=0, max_length=200, null=True),
        ),
    ]
