# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0010_auto_20181018_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhooduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
